config/routes.rb
Mp3store::Application.routes.draw do
  resources :albums
  resources :musics
  resources :artists
  root :to => "artists#index"
  match "songs" => "musics#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_and_belongs_to_many :artists
  has_many :musics
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_and_belongs_to_many :albums
  
  validates :first_name,
    :presence => true
    
  def name
    first_name + " " + last_name
  end 
end

app/models/music.rb
class Music < ActiveRecord::Base
  belongs_to :album
  validates :album, :presence => true
  validates :name, :presence => true, :uniqueness => true
  has_attached_file :mp3
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.xml
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.xml
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.xml
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.xml
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to(@artist, :notice => 'Artist was successfully created.') }
        format.xml  { render :xml => @artist, :status => :created, :location => @artist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.xml
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to(@artist, :notice => 'Artist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.xml
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to(artists_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # GET /musics
  # GET /musics.xml
  def index
    @musics = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @musics }
    end
  end

  # GET /musics/1
  # GET /musics/1.xml
  def show
    @music = Music.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @music }
    end
  end

  # GET /musics/new
  # GET /musics/new.xml
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @music }
    end
  end

  # GET /musics/1/edit
  def edit
    @music = Music.find(params[:id])
  end

  # POST /musics
  # POST /musics.xml
  def create
    @music = Music.new(params[:music])

    respond_to do |format|
      if @music.save
        format.html { redirect_to(@music, :notice => 'Music was successfully created.') }
        format.xml  { render :xml => @music, :status => :created, :location => @music }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @music.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /musics/1
  # PUT /musics/1.xml
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to(@music, :notice => 'Music was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @music.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.xml
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to(musics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album do |f| %>
  <% if @album.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being    saved:</h2>

     <ul>
     <% @album.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
  <%= f.input :name %>
  <%= f.input :release_date, :as => :date, :start_year => Date.today.year - 20 %>
  <%= f.association :artists, :as => :check_boxes %>
  <%= f.submit 'Save' %>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Release date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.release_date %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Release date:</b>
  <%= @album.release_date %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/artists/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.error_messages%>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :biography, :as => :text %>
  <%= f.input :date_of_birth, :as => :date, :start_year => Date.today.year - 90 %>
  <%= f.input :official_website, :as => :url %>
  <%= f.input :music_style %>
  <%= f.association :albums, :as => :check_boxes %>
  <%= f.submit 'Save' %>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Biography</th>
    <th>Date of birth</th>
    <th>Official website</th>
    <th>Music style</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.first_name %> <%= artist.last_name %></td>
	<td><%= artist.biography[0..100] %><%="..." if artist.biography.length > 100 %></td>
	<%-# how does it know to pull the length? #%>
    <td><%= artist.date_of_birth %></td>
    <td><%= artist.official_website %></td>
    <td><%= artist.music_style %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @artist.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @artist.last_name %>
</p>

<p>
  <b>Biography:</b>
  <%= @artist.biography %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @artist.date_of_birth %>
</p>

<p>
  <b>Official website:</b>
  <%= @artist.official_website %>
</p>

<p>
  <b>Music style:</b>
  <%= @artist.music_style %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3store</title>
  <%= stylesheet_link_tag :all  %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id='wrapper'>
	    <div id='store'>
	      <div id='top_navigation'>
	      <%= render_navigation %>
	      </div>
	      <div id='content' class='content'>
	      <%= yield %>
	      </div>
	    </div>
	  </div>
</body>
</html>

app/views/musics/_form.html.erb
<%= simple_form_for @music do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :length_in_sec, :as => :time %>
  <%= f.association :album %>
  <%= f.submit 'Save' %>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Length in sec</th>
    <th>Mp3 file name</th>
    <th>Mp3 content type</th>
    <th>Mp3 file size</th>
    <th>Mp3 updated at</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musics.each do |music| %>
  <tr>
    <td><%= music.name %></td>
    <td><%= music.length_in_sec %></td>
    <td><%= music.mp3_file_name %></td>
    <td><%= music.mp3_content_type %></td>
    <td><%= music.mp3_file_size %></td>
    <td><%= music.mp3_updated_at %></td>
    <td><%= music.album.try(:name) %></td>
    <td><%= link_to 'Show', music %></td>
    <td><%= link_to 'Edit', edit_music_path(music) %></td>
    <td><%= link_to 'Destroy', music, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @music.name %>
</p>

<p>
  <b>Length in sec:</b>
  <%= @music.length_in_sec %>
</p>

<p>
  <b>Mp3 file name:</b>
  <%= @music.mp3_file_name %>
</p>

<p>
  <b>Mp3 content type:</b>
  <%= @music.mp3_content_type %>
</p>

<p>
  <b>Mp3 file size:</b>
  <%= @music.mp3_file_size %>
</p>

<p>
  <b>Mp3 updated at:</b>
  <%= @music.mp3_updated_at %>
</p>

<p>
  <b>Album:</b>
  <%= @music.album.try(:name) %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>